# Generated by Django 5.1.2 on 2024-10-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.IntegerField(choices=[(0, 'reader'), (1, 'moderator'), (2, 'author')], default=0),
        ),
    ]
